# Setup
title:               OC-DB
tagline:            
description:         
url:                 http://oc-sudo.github.io/coding-wiki
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Olivia C
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
