# Setup
title:               OC wiki
tagline:             'For backup'
description:         'Useful documentation backup for easy reading.'
url:                 https://oc-sudo.github.io/coding-wiki/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Olivia C
  url:               https://oliviachen.info
  email:             olivia.hsu.cn@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y